require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 35

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Lint/MissingSuper:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
