require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

RSpec/ExampleLength:
  Enabled: false